// fetch popular movies
const FETCH_POPULAR_MOVIES_REQUEST = 'FETCH_POPULAR_MOVIES_REQUEST';
const FETCH_POPULAR_MOVIES_SUCCESS = 'FETCH_POPULAR_MOVIES_SUCCESS';
const FETCH_POPULAR_MOVIES_FAILURE = 'FETCH_POPULAR_MOVIES_FAILURE';

// fetch search movies
const FETCH_SEARCH_MOVIES_REQUEST = 'FETCH_SEARCH_MOVIES_REQUEST';
const FETCH_SEARCH_MOVIES_SUCCESS = 'FETCH_SEARCH_MOVIES_SUCCESS';
const FETCH_SEARCH_MOVIES_FAILURE = 'FETCH_SEARCH_MOVIES_FAILURE';

// clear state on unmount
const CLEAR_POPULAR_MOVIES = 'CLEAR_POPULAR_MOVIES';

const ADD_PAGE = 'ADD_PAGE';
const SUBSTRACT_PAGE = 'SUBSTRACT_PAGE';

export default {
  FETCH_POPULAR_MOVIES_REQUEST,
  FETCH_POPULAR_MOVIES_SUCCESS,
  FETCH_POPULAR_MOVIES_FAILURE,
  FETCH_SEARCH_MOVIES_REQUEST,
  FETCH_SEARCH_MOVIES_SUCCESS,
  FETCH_SEARCH_MOVIES_FAILURE,
  CLEAR_POPULAR_MOVIES,
  ADD_PAGE,
  SUBSTRACT_PAGE
};
