// fetch genre movies
const FETCH_GENRE_MOVIES_REQUEST = 'FETCH_GENRE_MOVIES_REQUEST';
const FETCH_GENRE_MOVIES_SUCCESS = 'FETCH_GENRE_MOVIES_SUCCESS';
const FETCH_GENRE_MOVIES_FAILURE = 'FETCH_GENRE_MOVIES_FAILURE';

const ADD_GENRE_PAGE = 'ADD_GENRE_PAGE';
const SUBSTRACT_GENRE_PAGE = 'SUBSTRACT_GENRE_PAGE';
const RESET_GENRE_PAGE = 'RESET_GENRE_PAGE';

export default {
  FETCH_GENRE_MOVIES_REQUEST,
  FETCH_GENRE_MOVIES_SUCCESS,
  FETCH_GENRE_MOVIES_FAILURE,
  ADD_GENRE_PAGE,
  SUBSTRACT_GENRE_PAGE,
  RESET_GENRE_PAGE
};
