// fetch genre movies
const FETCH_GENRE_MOVIES_REQUEST = 'FETCH_GENRE_MOVIES_REQUEST';
const FETCH_GENRE_MOVIES_SUCCESS = 'FETCH_GENRE_MOVIES_SUCCESS';
const FETCH_GENRE_MOVIES_FAILURE = 'FETCH_GENRE_MOVIES_FAILURE';

export default {
  FETCH_GENRE_MOVIES_REQUEST,
  FETCH_GENRE_MOVIES_SUCCESS,
  FETCH_GENRE_MOVIES_FAILURE
};
