// fetch recommended movies
const FETCH_RECOMMENDED_MOVIES_REQUEST = 'FETCH_RECOMMENDED_MOVIES_REQUEST';
const FETCH_RECOMMENDED_MOVIES_SUCCESS = 'FETCH_RECOMMENDED_MOVIES_SUCCESS';
const FETCH_RECOMMENDED_MOVIES_FAILURE = 'FETCH_RECOMMENDED_MOVIES_FAILURE';

export default {
  FETCH_RECOMMENDED_MOVIES_REQUEST,
  FETCH_RECOMMENDED_MOVIES_SUCCESS,
  FETCH_RECOMMENDED_MOVIES_FAILURE
};
